// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1646704774);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 0);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1646704804);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.region.update.updated", 1646704749);
user_pref("browser.search.region", "KR");
user_pref("browser.theme.dark-toolbar-theme", false);
user_pref("calendar.list.sortOrder", "169e8a62-8920-42ea-92e6-09570bd5fc0c");
user_pref("calendar.registry.169e8a62-8920-42ea-92e6-09570bd5fc0c.calendar-main-in-composite", true);
user_pref("calendar.registry.169e8a62-8920-42ea-92e6-09570bd5fc0c.disabled", true);
user_pref("calendar.registry.169e8a62-8920-42ea-92e6-09570bd5fc0c.name", "Home");
user_pref("calendar.registry.169e8a62-8920-42ea-92e6-09570bd5fc0c.type", "storage");
user_pref("calendar.registry.169e8a62-8920-42ea-92e6-09570bd5fc0c.uri", "moz-storage-calendar://");
user_pref("calendar.timezone.local", "Asia/Tokyo");
user_pref("calendar.ui.version", 3);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 1);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1646704757020");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 33);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppBuildId", "20220106182030");
user_pref("extensions.lastAppVersion", "91.5.0");
user_pref("extensions.lastPlatformVersion", "91.5.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webextensions.uuids", "{\"default-theme@mozilla.org\":\"a640e71a-6979-4e8b-8223-4e31ad6eaf80\",\"google@search.mozilla.org\":\"0195df2c-0d5e-4689-a1dd-88582412d8aa\",\"ddg@search.mozilla.org\":\"531c42bc-ec68-4dd8-a693-3aabd11e11c7\",\"amazondotcom@search.mozilla.org\":\"05a09a00-1a59-417d-943c-6144fbad169d\",\"wikipedia@search.mozilla.org\":\"e8767d5b-a385-4b11-b7d9-e0ff493356b0\",\"bing@search.mozilla.org\":\"eae6dfbd-e4db-4f6e-a2b0-a3ef33514c4b\"}");
user_pref("mail.ab_remote_content.migrated", 1);
user_pref("mail.folder.views.version", 1);
user_pref("mail.openMessageBehavior.version", 1);
user_pref("mail.spam.version", 1);
user_pref("mail.ui-rdf.version", 30);
user_pref("mailnews.database.global.datastore.id", "3f0f5343-d0f6-4f33-9cf2-807a2f159da");
user_pref("mailnews.headers.extraAddonHeaders", "autocrypt openpgp");
user_pref("mailnews.quotingPrefs.version", 1);
user_pref("mailnews.start_page_override.mstone", "91.5.0");
user_pref("mailnews.tags.$label1.color", "#FF0000");
user_pref("mailnews.tags.$label1.tag", "Important");
user_pref("mailnews.tags.$label2.color", "#FF9900");
user_pref("mailnews.tags.$label2.tag", "Work");
user_pref("mailnews.tags.$label3.color", "#009900");
user_pref("mailnews.tags.$label3.tag", "Personal");
user_pref("mailnews.tags.$label4.color", "#3333FF");
user_pref("mailnews.tags.$label4.tag", "To Do");
user_pref("mailnews.tags.$label5.color", "#993399");
user_pref("mailnews.tags.$label5.tag", "Later");
user_pref("mailnews.tags.version", 2);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.trr.blocklist_cleanup_done", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("toolkit.telemetry.cachedClientID", "770f10b5-5b4e-469d-b628-68967a4097e6");
user_pref("toolkit.telemetry.previousBuildID", "20220106182030");
